// AUTH
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_CHECK = "AUTH_CHECK";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

// LOADING
export const LOADING_STARTED = "LOADING_STARTED";
export const LOADING_FINISHED = "LOADING_FINISHED";

// IS_BUSY
export const BUSY_SET = "BUSY_SET";
export const BUSY_UNSET = "BUSY_UNSET";

// ALERT
export const ALERT_SET = "ALERT_SET";
export const ALERT_CLEAR = "ALERT_CLEAR";

// CONFIRM DIALOGUE
export const CONFIRM_SHOW = "CONFIRM_SHOW";
export const CONFIRM_HIDE = "CONFIRM_HIDE";

// TIMELINE ITEM
export const DELETE_TIMELINE_ITEM = "DELETE_TIMELINE_ITEM";
export const ADD_TIMELINE_ITEM = "ADD_TIMELINE_ITEM";
export const EDIT_TIMELINE_ITEM = "EDIT_TIMELINE_ITEM";
export const FETCH_EDIT_TIMELINE_ITEM = "FETCH_EDIT_TIMELINE_ITEM";
export const PULL_TIMELINE_ITEMS = "PULL_TIMELINE_ITEMS";
export const CLEAR_TIMELINE_FORM_VALUES = "CLEAR_TIMELINE_FORM_VALUES";
export const ORDER_TIMELINE_ITEMS = "ORDER_TIMELINE_ITEMS"
